events {
    worker_connections 1024;
}

http {
   upstream my_number_app{
# For all "server" replace 192.168.1.5 with ours IP-adress
# (for Linux terminal "ip -br a", for Windows cmd "ipconfig")
      server 192.168.1.5:8081;
      server 192.168.1.5:8082;
      server 192.168.1.5:8083;
   }

   server {
      listen 8080 default_server;
      listen [::]:8080 default_server;

      server_name localhost;

      location / {
        proxy_pass http://my_number_app;
        proxy_set_header Host $host;
      }
   }
}